### ISSUE TITLE
EPUBs don't work in iBooks

### ISSUE THREAD

**Issue by AABoyles** [AABoyles/LessWrong-Portable#4]
https://www.lesserwrong.com/posts/uQ3AgiaryeWNpDrBN/rationality-abridged#6Pv27HYgN45E8DxGH

**Comment by roryokane** [comment]
# Errors within *Rationality Abridged*

Here are all the errors I see when trying to read [the current ePub of *Rationality Abridged*](https://github.com/AABoyles/LessWrong-Portable/blob/00f010ef45dcf6e77e0e6f0bfef7870ffa8af404/output/RationalityAbridged.epub) within iBooks 1.15 for macOS. None of the chapters render after the horizontal line in the original web page.

- Errors on chapter “Rationality” ([original web page](https://perpetualcanon.blogspot.com/2018/01/the-first-book-of-rationality.html)):
    - error on line 46 at column 17: Opening and ending tag mismatch: br line 0 and div
- Errors on chapter “The first book of rationality”:
    - error on line 39 at column 20: Opening and ending tag mismatch: hr line 0 and div
- Errors on chapter “The second book of rationality”:
    - error on line 39 at column 20: Opening and ending tag mismatch: hr line 0 and div
- Errors on chapter “The third book of rationality” ([original web page](https://perpetualcanon.blogspot.com/2018/01/the-third-book-of-rationality.html)):
    - error on line 37 at column 332: Namespace prefix o on p is not defined
    - error on line 43 at column 19: Namespace prefix o on p is not defined
    - error on line 44 at column 138: Opening and ending tag mismatch: br line 0 and span
- Errors on chapter “The fourth book of rationality”:
    - error on line 39 at column 20: Opening and ending tag mismatch: hr line 0 and div
- Errors on chapter “The penultimate book of rationality”:
    - error on line 40 at column 20: Opening and ending tag mismatch: hr line 0 and div
- Errors on chapter “The final book of rationality”:
    - error on line 40 at column 20: Opening and ending tag mismatch: hr line 0 and div

## Screenshots

Screenshots of the entire book as rendered in iBooks, only 10 pages long, including the error messages:

<img width="1190" alt="pages 1–2" src="https://user-images.githubusercontent.com/79168/54493928-905afb80-48ab-11e9-93f8-faed6757d0ba.png">
<img width="1190" alt="pages 3–4" src="https://user-images.githubusercontent.com/79168/54493932-92bd5580-48ab-11e9-8578-2e18c6dcbaaf.png">
<img width="1190" alt="pages 5–6" src="https://user-images.githubusercontent.com/79168/54493933-94871900-48ab-11e9-9435-857b4bcaa2d6.png">
<img width="1190" alt="pages 7–8" src="https://user-images.githubusercontent.com/79168/54493936-95b84600-48ab-11e9-98bb-cccbc78a9119.png">
<img width="1190" alt="pages 9–10" src="https://user-images.githubusercontent.com/79168/54493937-97820980-48ab-11e9-8d65-834b4790af5a.png">

## Cover image

Also, iBooks displays only the cover image on one’s bookshelf, not a textual title next to it. The cover image is nothing but “Less Wrong”, so this makes it hard to identify the book:

<img width="348" alt="cover image of Rationality Abridged in iBooks" src="https://user-images.githubusercontent.com/79168/54493743-dd3dd280-48a9-11e9-9a90-a966a46c0274.png">

# Errors within *The Abridged Guide to Intelligent Characters*

I tested the epub version of *The Abridged Guide to Intelligent Characters* and it had errors too. I’ll just paste the first error; hopefully that will be enough to fix it, knowing the errors in the other book.

- Errors on chapter “Intelligent Characters”:
    - error on line 28 at column 2860: Opening and ending tag mismatch: br line 0 and span

**Comment by AABoyles** [comment]
Thanks for posting these, @roryokane! I'll take a look and see if I can get any more traction from this information.

**Comment by AABoyles** [comment]
Hey @roryokane! I just rebuilt Rationality: Abridged with a [new cover image](https://github.com/AABoyles/LessWrong-Portable/blob/master/images/RationalityAbridged.png) (so it should be a little more interpretable in the iBooks bookshelf). I have access to an Apple machine, and can now see/replicate the errors you're reporting. I'm trying to figure out how to correct them. Thanks again for reporting them!

**Comment by gavento** [comment]
I can see a similar set of errors in calibre:
Edit book -> Check for bugs -> see the report complaoning about `<br>` and `<hr>`s, if there are any

I think the issue is that the lesswrong content is HTML but epub is XHTML, so all tags must be closed or self closing (e.g. `<hr/>` here)

**Comment by droval** [comment]
I am not sure if this is related to this issue, but the Codex epub seems to be missing the content in the Cardiologists and Chinese Robbers chapter.

**Comment by AABoyles** [comment]
@gavento Yup, that's definitely a huge source of errors. Still thinking through a proper solution.

@droval Not sure, but that chapter is fixed in the epub now. (Still missing in the mobi, but fixing it is low priority ATM.)

Thanks for the input, all! I've rewritten a good deal of the logic specifically to get the codex working in iBooks. It isn't perfect, but it's at least generally readable. Accordingly, closing for now.
