### ISSUE TITLE
What urls should I add for this sequence?

### ISSUE THREAD

**Issue by NightMachinery** [AABoyles/LessWrong-Portable#8]
https://www.lesswrong.com/s/SqFbMbtxGybdS2gRs

Does it suffice to just add the first two articles?

**Comment by AABoyles** [comment]
Unfortunately, no. LWP only scrapes the pages you list for it, so to get the whole sequence you need to add a URL for every article in it.

**Comment by AABoyles** [comment]
Hey @NightMachinary! If you're still interested in generating an ebook of Highly Advanced Epistemology, I've added [the requisite meta file](https://github.com/AABoyles/LessWrong-Portable/blob/master/meta/epistemology.json) (see 169a08c9aff90c9cbe12e893674d1be3a83f7925). Alternately, [if you just want to read it...](https://github.com/AABoyles/LessWrong-Portable/blob/master/output/Epistemology.epub)
