### ISSUE TITLE
Scraping fails for all pages

### ISSUE THREAD

**Issue by Baranowski** [AABoyles/LessWrong-Portable#9]
LessWrong-Portable fails with `Scrape errors occurred: No book produced.`

Steps to reproduce:
1. Clone the repo
2. Follow the build instructions
3. 
```
$ nodejs build.js default
Scraping https://www.lesserwrong.com/posts/ANDbEKqbdDuBCQAnM/about-lesswrong-2-0
Couldn't correctly scrape /posts/ANDbEKqbdDuBCQAnM/about-lesswrong-2-0
Scrape errors occurred: No book produced.
```

Environment:
```
$ nodejs -v
v8.10.0
$ uname -soirv
Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 GNU/Linux
```

**Comment by AABoyles** [comment]
Yikes! Sorry about that, should be resolved by 5473044e536da98d89650d070f71b3a8698398b4

**Comment by Baranowski** [comment]
Thanks. I haven't given it a try yet. In the meantime, Oliver from the LW2.0 crew also gave it a shot: https://github.com/LessWrong2/LessWrong-Portable

**Comment by AABoyles** [comment]
Oh, nifty! Thanks for the tip!
